config/routes.rb
Rails.application.routes.draw do
	root "users#index"
	get "/", to: "users#index", as: "home"
	get "/signup", to: "users#new"
	post "/signup", to: "users#create"
	get "/show", to: "users#show", as: "show_user"
	get "/this/is/very/private", to: "users#current_user", as:"current_user"

	get "/login", to: "sessions#new"
	post "/login", to: "sessions#create"
	delete "/logout", to: "sessions#destroy", as: "logout"

	get "/hero/index", to: "heros#index", as: "hero_index"
	get "/playground", to: "heros#show", as: "playground"
	get "/new_hero", to: "heros#new", as: "new_hero"
	post "/new_hero", to: "heros#create"
	put "/hero/:id", to: "heros#update", as: "update_hero"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :hero

  def self.confirm(params)
    @user = User.find_by({name: params[:name]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::MimeResponds
  protect_from_forgery with: :exception
  include SessionsHelper
  include HerosHelper


end

app/controllers/heros_controller.rb
class HerosController < ApplicationController

	def index
		if current_user.hero != nil
			redirect_to playground_path
		else
			redirect_to new_hero_path
		end
	end

	def new
		@hero = Hero.new
		if current_user.hero != nil
			redirect_to playground_path
		end
	end

	def create
		current_user.hero = Hero.new(hero_params)
		redirect_to playground_path
	end

	def show
		set_user
		puts "kkk"
		@hero = current_user.hero
		respond_to :js, :html
		# respond_to do |f|
	 #    f.js { render :content_type => 'text/javascript' }
	 #    f.html
	 #  end
	end

	def update
		puts "heroupdateeee"
		puts params
		@hero = Hero.find(params[:id])
		if @hero.update(hero_params)
			set_user
		end
	end

	private
	def set_user
		# cookies.delete :user
    cookies[:hero_id] = current_user.hero.id
		cookies[:hero_atk] = current_user.hero.atk
		cookies[:hero_def] = current_user.hero.def
		cookies[:hero_agi] = current_user.hero.agi
		cookies[:hero_luk] = current_user.hero.luk
		cookies[:hero_wis] = current_user.hero.wis
		cookies[:hero_exp] = current_user.hero.exp
		cookies[:hero_lvl] = current_user.hero.level
  end

  def hero_params
  	params.permit(:level, :exp, :atk, :def, :luk, :agi, :wis)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
    @user = User.new
  end

  def create
    # confirm that email/password combination is correct
    @user = User.confirm(user_params)
    puts "user: #{@user}"
    if @user
      login(@user)
      flash[:success] = "Successfully logged in."      # <--- Add this flash notice
      # redirect_to show_user_path(@user[:id])
      redirect_to hero_index_path
    else
      redirect_to login_path
    end
	end

	def destroy
    logout
    flash[:success] = "Successfully logged out."        # <--- Add this flash notice
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			login(@user)
			flash[:success] = "Create Success"
			redirect_to root_path
		else
			flash[:error] = "oh no!"
			redirect_to sign_up_path
		end
	end

	def current_user
		render json: {name: current_user}
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heros_helper.rb
module HerosHelper
	WARRIOR_SET = {:level => 1, :atk => 31, :def => 40, :agi => 10, :luk => 30, :wis => 5, :exp => 0}
	ARCHER_SET = {:level => 1, :atk => 40, :def => 25, :agi => 60, :luk => 30, :wis => 15, :exp => 0}
	MAGE_SET = {:level => 1, :atk => 80, :def => 10, :agi => 15, :luk => 30, :wis => 35, :exp => 0}

	def hero_params
		hero_info = params.require(:hero).permit(:name, :job)
		case hero_info[:job]
			when "Warrior"
			  hero_info = hero_info.merge WARRIOR_SET
			when "Archer"
				hero_info = hero_info.merge ARCHER_SET
			when "Mage"
			  hero_info = hero_info.merge MAGE_SET
		end
		return hero_info
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def logout
    session[:user_id] = "none"
    @current_user = false
   end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

	def user_params
		params.require(:user).permit(:name, :password)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/heros/new.html.erb
<h1 style="text-align: center">Create your hero!</h1>

<div style="margin-top: 20px;" class="row">
<div class="col-xs-4 col-xs-offset-4">
<%= form_with model: @hero, url: new_hero_path, class: "form-horizontal" do |form| %>
<div class="form-group">
		<%= form.label :name, "Hero name:" %>
		<%= form.text_field(:name, class: 'form-control') %>
</div>
<div class="form-group">
		<%= form.label :job, "Hero class:" %>
		<%= form.select :job, ['Warrior', 'Archer', 'Mage'] %>
</div>

<div class="form-group">
		<%= form.submit('Create', class: 'btn-sm btn-primary') %>
</div>
<% end %>
</div>
</div>

app/views/heros/show.html.erb
<p>This is the adventure of:</p>
<p><%= @hero.name %></p>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1" id="game-box">
		<p id="game-content" class="col-xs-6"></p>
	</div>
</div>
<div class="row">
	<div class="col-xs-4 col-xs-offset-4">
		<form class="form-inline" id="action-form">
		  <div class="form-group">
		    <label class="sr-only">You do: </label>
		    <input type="text" class="form-control-plaintext" placeholder="type here...">
		  </div>
		  <button type="submit" class="btn btn-primary">Act</button>
		</form>
		<p class="col-xs-12">Game Commands: </br>
		move = search / escape monsters</br>
		atk = attack monster
		</p>
	</div>
</div>

app/views/heros/show.js.erb
// $(document).ready(function(){
//   $("#action-form").on('submit', function(e){
//     e.preventDefault()
//     console.log($(".form-control-plaintext").val())
//     if($(".form-control-plaintext").val() === 'move'){
//       $.get("/this/is/very/private", function(result){
//         console.log(result)
//       })
//       console.log ()
//     }
//     $('#game-box').scrollTop($('#game-box')[0].scrollHeight);
//   })
// });
console.log("asd")
alert("test")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>world of wordcraft</title>
    <!-- <link rel="icon" href=""> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- STYLESHEETS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- HAVE TO INCLUDE VALIDATOR TO USE VALIDATOR!!!! THIS THING TOOK ME AN HOUR TO SOLVE -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>

    <!-- FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Oregano" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="homepage-container">
	<h1>World of Wordcraft</h1>
	<hr>
  <% flash.each do |name, msg| %>
    <% if name == "success" %>
      <p class="alert alert-success">
    <% else %>
      <p class="alert alert-error">
    <% end %>
      <strong> <%= name.capitalize %>: <%= msg %> </strong>
    </p>
  <% end %>
  <% if !@current_user %>
    <%= link_to "sign up", signup_path, class: "btn btn-primary" %>
    <%= link_to "log in", login_path, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "log out", logout_path, class: "btn btn-primary", method: "delete" %>
  <% end %>
	
    <%= yield %>
</div>
  </body>
</html>

app/views/users/new.html.erb
<h1 style="text-align: center">Sign Up</h1>

<div style="margin-top: 20px;" class="row">
<div class="col-xs-4 col-xs-offset-4">
<%= form_with model: @user, url: signup_path, class: "form-horizontal" do |form| %>
<div class="form-group">
		<%= form.label :name, "Username:" %>
		<%= form.text_field(:name, class: 'form-control') %>
</div>
<div class="form-group">
		<%= form.label :password, "Password:" %>
		<%= form.text_field(:password, class: 'form-control') %>
</div>
<div class="form-group">
		<%= form.submit('Sign Up', class: 'btn-sm btn-primary') %>
</div>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<h1>yo</h1>